version: "3.9"

services:

  node.contmysql:
    image: mysql:8.0.29
    ports:
      - '3307:3306'
    environment: 
      MYSQL_DATABASE: 'projectExa'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: 'enter123@'
      MYSQL_ROOT_PASSWORD: 'enter123@'
    volumes:
      - ./mysql-initdb:/docker-entrypoint-initdb.d

  node.app:
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3100:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
      
volumes:
  mysql-data: