# Usa una imagen base de Nginx
FROM nginx:alpine

# Copia el contenido del directorio 'html' al directorio de contenido de Nginx
COPY docker/web /usr/share/nginx/html/

# Expone el puerto 80
EXPOSE 80
